const ChatbotStates = Object.freeze({
    PENDIENTE_COMPRA_DROPI: 'PENDIENTE_COMPRA_DROPI',
    PENDIENTE_NOTIFICACION_GUIA: 'PENDIENTE_NOTIFICACION_GUIA',
    NOTIFICADO_GUIA: 'NOTIFICADO_GUIA',
    CANCELADO: 'CANCELADO'
});

module.exports = { ChatbotStates };